### PR TITLE
Initial setup suggestion for mkdocs based Soar documentation online

### PR DESCRIPTION
**Pull request by moschmdt**
**General information**

This is a suggestion for the Soar documentation using the [mkdocs material](https://squidfunk.github.io/mkdocs-material/) theme 
and CI features for publishing and checking links.

A temporary preview for inspection is available at [moschmdt.github.io/Documentation](
https://moschmdt.github.io/Documentation/)

The structure makes use of the [documentation system](https://documentation.divio.com/#about-the-system). I would suggest to put the Soar manual in a separate folder since it could fit in the _reference_ and _explanation_ category depending on the chapter.

I have already added some pages for testing and visualisation.

**Automatic Link Checks**

The CI for automatic link checks (check_links.yml) has some false positives and some links that do not work right now. How do you want to proceed about that @garfieldnate? 

Other pages and the manual currently converted in [moschmdt/Release-Support](https://github.com/moschmdt/Release-Support/tree/documentation) will follow in subsequent PRs once this is approved.

**Related**
- https://github.com/SoarGroup/Release-Support/issues/9
- https://github.com/SoarGroup/Release-Support/pull/12

### CODE REVIEW

**Comment by garfieldnate** [comment]
I love that there's a dead link checker!

* BSD license is here: https://opensource.org/license/bsd-2-clause/
* Andrew Nuxoll's page is here: https://opensource.org/license/bsd-2-clause/
* I can't find any modern equivalent for the isi institute one, so I'd just remove it.
* The MAVERICK group homepage was moved to here: https://u.cs.biu.ac.il/~kaminkg/maverick/
* I would remove the section about the University of Portsmouth. I have to go back 10 years on Wayback Machine to find a live link.
* The shiwali.me one can be found here now: https://aaai.org/papers/05662-learning-grounded-language-through-situated-interactive-instruction/
* The http://arc.aiaa.org/doi/abs/10.2514/1.53282?journalCode=jacic link works fine in the browser, but gives 403 for wget as well as Python. I think you should disable the check for that one: https://github.com/marketplace/actions/markdown-link-check#disable-check-for-some-links.

**Comment by garfieldnate** [comment]
This is my preferred editorconfig:

```
[*]
end_of_line = lf
trim_trailing_whitespace = true
charset = utf-8
indent_style = space
indent_size = 4
insert_final_newline = true
tab_width = 4
```

I notice you have a typo (flase instead of false) in  yours; but I'm not sure why you'd like to turn off whitespace trimming, either.

**Comment by moschmdt** [comment]
Apparently whitespaces at the end of lines in Markdown are a style feature for hard line breaks and it is not considered good practice to replace all line endings since this could break the format of the document. There is a discussion about this on [stackoverflow](https://stackoverflow.com/questions/36583502/how-to-force-a-linebreak).

Maybe it is better to catch too many white space endings with a linter similar to the link check CI job?

**Comment by moschmdt** [comment]
> I love that there's a dead link checker!
> 
> * BSD license is here: https://opensource.org/license/bsd-2-clause/
> * Andrew Nuxoll's page is here: https://opensource.org/license/bsd-2-clause/
> * I can't find any modern equivalent for the isi institute one, so I'd just remove it.
> * The MAVERICK group homepage was moved to here: https://u.cs.biu.ac.il/~kaminkg/maverick/
> * I would remove the section about the University of Portsmouth. I have to go back 10 years on Wayback Machine to find a live link.
> * The shiwali.me one can be found here now: https://aaai.org/papers/05662-learning-grounded-language-through-situated-interactive-instruction/
> * The http://arc.aiaa.org/doi/abs/10.2514/1.53282?journalCode=jacic link works fine in the browser, but gives 403 for wget as well as Python. I think you should disable the check for that one: https://github.com/marketplace/actions/markdown-link-check#disable-check-for-some-links.

The link to Andrew Nuxoll’s page also points to the BSD license?

**Comment by garfieldnate** [comment]
That was a typo for me :D Andrew's page is here: https://www.up.edu/directory/Andrew-Nuxoll.html

I'm a bit horrified to learn for the first time that Markdown uses trailing whitespace to mean something. I don't like invisible stuff having meaning, but I guess that's the spec! Here's an updated .editorconfig:

```
[*]
end_of_line = lf
trim_trailing_whitespace = true
charset = utf-8
indent_style = space
indent_size = 4
insert_final_newline = true
tab_width = 4

[*.md]
# Trailing whitespace is meaningful in markdown;
# see https://daringfireball.net/projects/markdown/syntax#block
trim_trailing_whitespace = false
```

**Comment by moschmdt** [comment]
Finally the automatic link check does work. I had to disable the automatic link check on the BSD license as well.

**Comment by garfieldnate** [comment]
Wonderful, thank you very much for all your efforts!

**Comment by garfieldnate** [comment]
I'm going to rename the repo from Documentation to documentation because it's very strange to have a required uppercase in the URL. Sorry for the inconvenience (you'll just need to change your remote URL).

**Pull request merged**
