### PR TITLE
Add CLI documentation from Github Wiki

### PR DESCRIPTION
**Pull request by moschmdt**
Just copied the CLI documentation over from the GitHub Wiki and added some files that were linked to in other documentation documents (to be added via another PR) - added files are still empty.

The tutorials and the manual link to those documents, thus they need to be added prior to the manual and tutorials.

### CODE REVIEW

**Comment by moschmdt** [comment]
Any idea about this link: <http://webdocs.cs.ualberta.ca/~sutton/papers/sutton-92a.pdf>

**Comment by garfieldnate** [comment]
Hey this is cool, thank you!

Looks like Rich Sutton has a new website: http://incompleteideas.net/papers/sutton-92a.pdf.

**Comment by garfieldnate** [comment]
This wiki text also included in the manual: https://github.com/SoarGroup/Release-Support/blob/master/ManualSource/wikicmd/gen_tex.sh.

I suspect that if we maintain a markdown version instead of the Wiki that processing it into the manual will be a lot simpler.

No one has edited the Wiki in 5 years, so I think it's probably okay to not use it anymore. We'll need to take the Wiki down and point users here.

**Comment by moschmdt** [comment]
> This wiki text also included in the manual: https://github.com/SoarGroup/Release-Support/blob/master/ManualSource/wikicmd/gen_tex.sh.
> 
> I suspect that if we maintain a markdown version instead of the Wiki that processing it into the manual will be a lot simpler.
> 
> No one has edited the Wiki in 5 years, so I think it's probably okay to not use it anymore. We'll need to take the Wiki down and point users here.

Yes, it will be a lot easier since running a CI pipeline with pandoc to build the SoarManual will be straight forward. 

I have a solution ready ([CI pipeline](https://github.com/moschmdt/documentation/blob/soar_manual/.github/workflows/build_pdf.yml) and [build script](https://github.com/moschmdt/documentation/blob/soar_manual/docs/soar_manual/build.sh)) but awaiting the merge of this PR so paths and dependencies are resolved.

**Comment by garfieldnate** [comment]
Thank you!

**Pull request merged**
